### ISSUE TITLE
网络请求那一块  稳定了吗？

### ISSUE THREAD

**Issue by momoc** [AnyLifeZLB/MVP-Dagger2-Rxjava2#14]
网络请求那一块  稳定了吗？
我打算  集成在项目里面

**Comment by AnyLifeZLB** [comment]
已经稳定了，我本月初已经在正式项目使用了，根据你自己的项目要修改一下东西。
今天的PR 根据反馈修正了http 请求WaitDialog 导致的内存泄漏
